### PR TITLE
chore: licence headers

### PR DESCRIPTION
**Pull request by quesebifurcan**
Add licence headers to aether-ui.

Fix typo (`anx -> an`) in all existing licence headers.

### CODE REVIEW

**Comment by obdulia-losantos** [comment]
Do not forget the scss files :wink:

**Comment by obdulia-losantos** [comment]
:+1:

**Review by obdulia-losantos — DISMISSED** [review]

**Review by lordmallam — DISMISSED** [review]

**Review by admbtlr — DISMISSED** [review]
LGTM!

**Review by admbtlr — APPROVED** [review]
Still LGTM!

**Pull request merged**
