### PR TITLE
fix: make client tests return a non-zero exit code on test failure.

### PR DESCRIPTION
**Pull request by quesebifurcan**
Make client tests return a non-zero exit code on test failure.

### CODE REVIEW

**Comment by admbtlr** [comment]
So is it expected that this PR fails on Travis?

**Comment by quesebifurcan** [comment]
@adamvert yes, that's the fix. Shawn is working on an update to the client code to make it pass.

**Comment by shawnsarwar** [comment]
Issues are fixed and it's ready for merge into 150.

**Review by admbtlr — APPROVED** [review]
LGTM

**Pull request closed without merging**
