### PR TITLE
Feat: docker versioning

### PR DESCRIPTION
**Pull request by MrPink**
* This currently breaks because of the directory structure  i.e `aether-odk-module`

### CODE REVIEW

**Review by shawnsarwar — COMMENTED** [review]
If I understand correctly, now if we run release.sh it'll we'll make new images and send them to docker hub as the version we set in aether-kernel/VERSION? Or do we need to set each version manually before we release?

**Comment by MrPink** [comment]
@shawnsarwar it sets whatever is in VERSION correct, I guess having a git tag creation script that you can run yourself would also be beneficial

**Comment by admbtlr** [comment]
Wouldn't it make sense to have just one VERSION file for the whole repo, since we're going to be releasing everything in lockstep?

**Comment by MrPink** [comment]
@adamvert @quesebifurcan @shawnsarwar I could set a Travis env for the version and pass it in as a build-arg, we can have a symbolic `VERSION` file in the root of the repository

**Comment by quesebifurcan** [comment]
@MrPink that sounds good. Would simplify things a bit and still make version bumping subject to code review.

**Comment by admbtlr** [comment]
So you mean you would set the env var based on the value contained in the `VERSION` file? If so, 👍

**Comment by MrPink** [comment]
@adamvert yeah exactly

**Review by admbtlr — APPROVED** [review]
LGTM

**Review by quesebifurcan — APPROVED** [review]
Nice!

**Pull request merged**
