### PR TITLE
chore: internal network name

### PR DESCRIPTION
**Pull request by obdulia-losantos**
Sorry but I had the same problem as Travis locally once I purged my local images :disappointed:

### CODE REVIEW

**Review by admbtlr — DISMISSED** [review]

**Review by shawnsarwar — CHANGES_REQUESTED** [review]
It looks like this is available on 3.5 +
https://forums.docker.com/t/set-default-network-name-for-compose/36779/3

**Comment by shawnsarwar** [comment]
@obdulia-losantos I'm going to try to mess with this on the bootstrap as we'll have the same issue there. I'll let you know if I find a fix.

**Comment by obdulia-losantos** [comment]
Let's try then :crossed_fingers:

**Comment by obdulia-losantos** [comment]
But in this case `extends` is not supported :unamused:

**Comment by obdulia-losantos** [comment]
This is becoming a nightmare... I'll try it later

**Pull request closed without merging**
