### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by obdulia-losantos**
This is still a manual task :disappointed_relieved:

### CODE REVIEW

**Review by quesebifurcan — DISMISSED** [review]

**Comment by admbtlr** [comment]
Did you see the Travis error here: https://travis-ci.com/eHealthAfrica/aether/jobs/154845812 ?

**Comment by adamvert** [comment]
Please don't merge this until I fully understand where these commits are coming from!

**Comment by obdulia-losantos** [comment]
It fails randomly :woman_shrugging:

**Comment by obdulia-losantos** [comment]
Also that isn't in this PR...

**Comment by admbtlr** [comment]
No, I know - it's on the release branch that I made. I was just wondering whether something in this PR addressed that.

**Comment by obdulia-losantos** [comment]
Nop, we need to check the integration tests again and find out the race condition... because this looks like a race condition.

**Comment by admbtlr** [comment]
Can you please rename this branch to something like `chore: upgrade dependencies` and remove the VERSION file change please? The we can merge it into develop and cherry pick it onto `release-1.0`

**Comment by obdulia-losantos** [comment]
@adamvert is it ready now?

**Review by admbtlr — APPROVED** [review]

**Pull request merged**
