### PR TITLE
test: (ui) return kernel url to ui

### PR DESCRIPTION
**Pull request by lordmallam**
Displays published pipeline metadata (submission url and sample data)

#### Related JIRA ticket [AET-287](https://jira.ehealthafrica.org/browse/AET-287)

### CODE REVIEW

**Comment by obdulia-losantos** [comment]
This is the way it's done in gather

https://github.com/eHealthAfrica/aether/blob/develop/aether-ui/aether/ui/webpack.common.js#L65-L70
`webpack.common.js`
```javascript
    // new plugin
    new webpack.EnvironmentPlugin({
      AETHER_KERNEL_URL: null, // this takes the env var
      // ...
    }),
```

`assets/utils/env.jsx`
```javascript

export const AETHER_KERNEL_URL = process.env.AETHER_KERNEL_URL

```

`assets/utils/env.spec.jsx`
```javascript

import assert from 'assert'

const TEST_ENV = process.env

describe('environment constants', () => {
  beforeEach(() => {
    // necessary to remove `require` cache
    jest.resetModules()

    // assign default environment variables
    process.env = Object.assign(
      {},
      process.env,
      {
        AETHER_KERNEL_URL: 'http://kernel-test:9001'
      }
    )
  })

  afterEach(() => {
    process.env = TEST_ENV
  })

  it('should take environment variables', () => {
    const envVars = require('./env')

    assert.equal(envVars.AETHER_KERNEL_URL, 'http://kernel-test:9001')
  })
})
```

With this you don't need to create a view to return the kernel server url

**Review by shawnsarwar — DISMISSED** [review]
Looks good from a requirements standpoint.

**Comment by lordmallam** [comment]
@obdulia-losantos I thought about that approach and decided to go with using `views` because it utilises the `get_kernel_server_url` function from the `common` module which is widely used across modules. Using the webpack method will add an extra layer of complexity in terms of code maintenance. In light of the microservices architecture, I think its best we have the business logic for determining the kernel url in one place.

**Review by quesebifurcan — CHANGES_REQUESTED** [review]
@lordmallam Would it be possible to reuse the kernel mapping url that you get from kernel whenever you successfully post a mapping? The response will always contain the same url we are rebuilding here https://github.com/eHealthAfrica/aether/blob/d0932403fe4d93cf9f53c5c2b016df5cd76b5823/aether-ui/aether/ui/assets/apps/pipeline/InfoButton.jsx#L26. And this could be stored in the ui database, along with the other kernel references.

**Comment by lordmallam** [comment]
@quesebifurcan The mapping id is already stored along with refs to other kernel artefacts. I don't think it's necessary storing the url in the db if it can be determined on the fly. Also, incase the host changes.

**Review by quesebifurcan — APPROVED** [review]

**Pull request merged**
