### PR TITLE
chore: split ui webpack image setup

### PR DESCRIPTION
**Pull request by obdulia-losantos**
@adamvert this is what I meant with splitting webpack and django apps in ui. :crossed_fingers:

### CODE REVIEW

**Review by shawnsarwar — DISMISSED** [review]

**Comment by admbtlr** [comment]
So this will work from the image without runnning `ui-webpack-base`?

**Comment by obdulia-losantos** [comment]
Right, `ui-webpack` is only needed to develop the react app.

**Comment by obdulia-losantos** [comment]
The only issue is that you need nginx to serve the static pages :grimacing:

**Comment by obdulia-losantos** [comment]
or we need to include the serve static in the url patterns....

https://docs.djangoproject.com/en/2.0/howto/static-files/#serving-static-files-during-development

**Review by admbtlr — DISMISSED** [review]
LGTM! what do you think @quesebifurcan?

**Review by quesebifurcan — DISMISSED** [review]

**Comment by obdulia-losantos** [comment]
I still want to make more tests on this branch and check all the possible cases before merging it, I did it so much fast without time to test.

**Comment by obdulia-losantos** [comment]
@adamvert @shawnsarwar @quesebifurcan @tooxie 

I finally managed to start the "UI" container without webpack and serve the static files. What I couldn't solve was the `docker-compose run ui-webpack build` requirement. I don't know why but the container didn't find the files in the copied folder so I removed all the "node" steps in the `Dockerfile`.

:crossed_fingers:

**Comment by admbtlr** [comment]
So it's still necessary to run `docker-compose run ui-webpack build`?

**Comment by obdulia-losantos** [comment]
But only locally, it's suppose that the docker hub image already has the "distributed" files (I included the instruction in the `release.sh` script).

I need to check that but I cannot without pushing it to docker hub and pulling the image :woman_shrugging:

**Comment by admbtlr** [comment]
Ah, I missed the lines you added to `release.sh`... @shawnsarwar fixed the deployment yesterday so that we get `x.x.x-rc` images, so maybe if we merge this PR we can get a release candidate image built and test it

**Review by admbtlr — APPROVED** [review]

**Pull request merged**
