### PR TITLE
fix: reactivate UI tests in travis

### PR DESCRIPTION
**Pull request by obdulia-losantos**
This branch should fix all the Travis issues we had with the UI container :crossed_fingers:

### CODE REVIEW

**Comment by lordmallam** [comment]
Travis failing here https://travis-ci.com/eHealthAfrica/aether/jobs/146915070#L1548, due to duplicate keys https://github.com/eHealthAfrica/aether/blob/parallel-ui-test/aether-ui/aether/ui/assets/conf/sass-lint.yml#L59

**Comment by obdulia-losantos** [comment]
This PR should not pass the test, but this branch `parallel-extraction` must :wink:

**Comment by lordmallam** [comment]
Agreed. But this is a build error not a test failing

**Comment by obdulia-losantos** [comment]
The only failing test is the UI one; Kernel, ODK, Couchdb-Sync and UI-assets passed :grimacing: 

Obviously, integration tests are other point.

**Review by lordmallam — APPROVED** [review]

**Pull request merged**
