### PR TITLE
fix: only pass strings to stderr

### PR DESCRIPTION
**Pull request by quesebifurcan**
Prior to this commit, the extract_entities command passed
a dict to stderr, resulting in the following error:
```
AttributeError: 'dict' object has no attribute 'endswith'
```

### CODE REVIEW

**Comment by shawnsarwar** [comment]
Why are there two PRs for this? #462 is approved.

**Comment by obdulia-losantos** [comment]
One for `develop` and another for the `release-xxx` branch :woman_shrugging:

**Review by obdulia-losantos — APPROVED** [review]

**Comment by quesebifurcan** [comment]
@shawnsarwar What Obdulia said. Also, we're holding off on merging https://github.com/eHealthAfrica/aether/pull/462 until we can sync with Will re:0.11 deployments.

**Comment by shawnsarwar** [comment]
@obdulia-losantos @quesebifurcan Can this be merged?

**Review by obdulia-losantos — APPROVED** [review]

**Pull request merged**
