### PR TITLE
feat: create passthrough mapping from AVRO schema

### PR DESCRIPTION
**Pull request by obdulia-losantos**
This is the first step to integrate Gather 3 with Aether CouchDB-Sync module.

Instead of creating the artefacts in the module just pushed the AVRO schema and let Kernel create all the necessary and related items.

Include this new feature also in the ODK module.

The endpoint in Kernel is `.../projects/{pk}/avro-schemas/`

Expected payload:

```python
    {
        # this is optional, indicates the action to execute:
        #   "create", creates the missing objects but does not update the existing ones
        #   otherwise creates/updates the given objects
        'action': 'upsert',

        # this is optional, if missing the method will assign a random name
        "name": "project name (optional but unique)",

        # this is optional, for each entry the method will
        # create/update a schema and also link it to the project
        # (projectschema entry) creating the passthrough mapping
        "avro_schemas": [
            {
                "id": "schema id (optional and shared with the linked artefacts)",
                "definition": {
                    # the avro schema
                }
            },
            # ...
        ],
    }
```

### CODE REVIEW

**Review by shawnsarwar — DISMISSED** [review]
I like the approach. I didn't realize we had a one-stop upsert for project + artifacts already. I'm sure you already have a patch ready for mapping-sets :page_with_curl:

**Comment by shawnsarwar** [comment]
I focused on the Kernel aspects as I don't know nearly as much about the CBD sync module.

**Comment by admbtlr** [comment]
This works well! The one thing I would say is that the endpoint should probably be `/propagate` rather than `/propagates`.

**Comment by obdulia-losantos** [comment]
### Successful propagation

image

### Propagation with error
image

**Comment by adamvert** [comment]
I just tried to merge this branch into `parallel-extraction` to see if I could everything working, but when I created a survey with an XForm, I got this error:

```
{"description":"Unexpected response from Aether Kernel server while trying to create/update the project artefacts \"d3cf65ec-141e-4569-a76d-995375b1c13f\".
Response: IntegrityError at /projects/d3cf65ec-141e-4569-a76d-995375b1c13f/avro-schemas/
duplicate key value violates unique constraint \"kernel_schema_name_2afbbd49_uniq\"
DETAIL:  Key (name)=(AetherWalkthroughMicrocensus_Vpkhiffvvdnddqeusecaf) already exists.


Request Method: PATCH
Request URL: http://kernel:8000/projects/d3cf65ec-141e-4569-a76d-995375b1c13f/avro-schemas/
Django Version: 1.11.15
Python Executable: /usr/local/bin/python
Python Version: 3.6.6
Python Path: ['/code', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages']
Server time: Thu, 4 Oct 2018 15:21:24 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.postgres',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'storages',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_csv',
 'corsheaders',
 'django_prometheus',
 'aether.common',
 'debug_toolbar',
 'django_filters',
 'rest_framework_filters',
 'reversion',
 'reversion_compare',
 'aether.kernel',
 'drf_yasg']
Installed Middleware:
['django_prometheus.middleware.PrometheusBeforeMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']


Traceback:  

File \"/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py\" in execute
  64.                 return self.cursor.execute(sql, params)

File \"/usr/local/lib/python3.6/site-packages/django_prometheus/db/common.py\" in execute
  63.                 return super(CursorWrapper, self).execute(*args, **kwargs)
  
    
      The above exception (duplicate key value violates unique constraint \"kernel_schema_name_2afbbd49_uniq\"
DETAIL:  Key (name)=(AetherWalkthroughMicrocensus_Vpkhiffvvdnddqeusecaf) already exists.
) was the direct cause of the following exception:
    
  

File \"/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py\" in inner
  41.             response = get_response(request)

File \"/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py\" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File \"/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py\" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File \"/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py\" in wrapped_view
  58.         return view_func(*args, **kwargs)

File \"/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py\" in view
  103.             return self.dispatch(request, *args, **kwargs)

File \"/usr/local/lib/python3.6/site-packages/rest_framework/views.py\" in dispatch
  483.             response = self.handle_exception(exc)

File \"/usr/local/lib/python3.6/site-packages/rest_framework/views.py\" in handle_exception
  443.             self.raise_uncaught_exception(exc)

File \"/usr/local/lib/python3.6/site-packages/rest_framework/views.py\" in dispatch
  480.             response = handler(request, *args, **kwargs)

File \"/code/aether/kernel/api/views.py\" in avro_schemas
  111.         return self.__upsert_schemas(request, pk)

File \"/code/aether/kernel/api/views.py\" in __upsert_schemas
  256.             avro_schemas=data.get('avro_schemas', []),

File \"/code/aether/kernel/api/project_artefacts.py\" in upsert_project_with_avro_schemas
  218.         mappings=mappings,

File \"/usr/local/lib/python3.6/contextlib.py\" in inner
  52.                 return func(*args, **kwds)

File \"/code/aether/kernel/api/project_artefacts.py\" in upsert_project_artefacts
  100.             type=raw_schema.get('type', 'record'),

File \"/code/aether/kernel/api/project_artefacts.py\" in __upsert_instance
  270.         item.save()

File \"/usr/local/lib/python3.6/site-packages/django/db/models/base.py\" in save
  808.                        force_update=force_update, update_fields=update_fields)

File \"/usr/local/lib/python3.6/site-packages/django/db/models/base.py\" in save_base
  838.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

File \"/usr/local/lib/python3.6/site-packages/django/db/models/base.py\" in _save_table
  924.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

File \"/usr/local/lib/python3.6/site-packages/django_prometheus/models.py\" in _do_insert
  35.             return super(Mixin, self)._do_insert(*args, **kwargs)

File \"/usr/local/lib/python3.6/site-packages/django/db/models/base.py\" in _do_insert
  963.                                using=using, raw=raw)

File \"/usr/local/lib/python3.6/site-packages/django/db/models/manager.py\" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File \"/usr/local/lib/python3.6/site-packages/django/db/models/query.py\" in _insert
  1076.         return query.get_compiler(using=using).execute_sql(return_id)

File \"/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py\" in execute_sql
  1112.                 cursor.execute(sql, params)

File \"/usr/local/lib/python3.6/site-packages/debug_toolbar/panels/sql/tracking.py\" in execute
  176.         return self._record(self.cursor.execute, sql, params)

File \"/usr/local/lib/python3.6/site-packages/debug_toolbar/panels/sql/tracking.py\" in _record
  117.             return method(sql, params)

File \"/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py\" in execute
  79.             return super(CursorDebugWrapper, self).execute(sql, params)

File \"/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py\" in execute
  64.                 return self.cursor.execute(sql, params)

File \"/usr/local/lib/python3.6/site-packages/django/db/utils.py\" in __exit__
  94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)

File \"/usr/local/lib/python3.6/site-packages/django/utils/six.py\" in reraise
  685.             raise value.with_traceback(tb)

File \"/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py\" in execute
  64.                 return self.cursor.execute(sql, params)

File \"/usr/local/lib/python3.6/site-packages/django_prometheus/db/common.py\" in execute
  63.                 return super(CursorWrapper, self).execute(*args, **kwargs)

Exception Type: IntegrityError at /projects/d3cf65ec-141e-4569-a76d-995375b1c13f/avro-schemas/
Exception Value: duplicate key value violates unique constraint \"kernel_schema_name_2afbbd49_uniq\"
DETAIL:  Key (name)=(AetherWalkthroughMicrocensus_Vpkhiffvvdnddqeusecaf) already exists.

Request information:
USER: admin

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data

META:
ADMIN_PASSWORD = 'adminadmin'
ADMIN_TOKEN = '40e156808591a49659253fd9b65b0d44'
ADMIN_USERNAME = 'admin'
APP_NAME = 'Aether Kernel'
CONTENT_LENGTH = '4321'
CONTENT_TYPE = 'application/json'
CSRF_COOKIE_DOMAIN = '.aether.local'
DB_NAME = 'aether'
DEBUG = 'true'
DJANGO_SECRET_KEY = '8e5816f992460dc2b0a0a018f446c758'
DJANGO_SETTINGS_MODULE = 'aether.kernel.settings'
DJANGO_STORAGE_BACKEND = 'filesystem'
GATEWAY_INTERFACE = 'CGI/1.1'
GPG_KEY = '0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D'
HOME = '/root'
HOSTNAME = 'kernel.aether.local'
HTTP_ACCEPT = '*/*'
HTTP_ACCEPT_ENCODING = 'gzip, deflate'
HTTP_AUTHORIZATION = 'Token 40e156808591a49659253fd9b65b0d44'
HTTP_CONNECTION = 'keep-alive'
HTTP_HOST = 'kernel:8000'
HTTP_USER_AGENT = 'python-requests/2.19.1'
KERNEL_READONLY_DB_PASSWORD = '0aa5e169a431fc61667385c8f347bb04'
KERNEL_READONLY_DB_USERNAME = 'readonlyuser'
LANG = 'C.UTF-8'
PATH = '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PATH_INFO = '/projects/d3cf65ec-141e-4569-a76d-995375b1c13f/avro-schemas/'
PGHOST = 'db'
PGPASSWORD = '9fcd99cc2dee774fb8f721dee7842b63'
PGPORT = '5432'
PGUSER = 'postgres'
PWD = '/code'
PYTHON_PIP_VERSION = '18.0'
PYTHON_VERSION = '3.6.6'
QUERY_STRING = ''
REMOTE_ADDR = '172.22.0.5'
REMOTE_HOST = ''
REQUEST_METHOD = 'PATCH'
RUN_MAIN = 'true'
SCRIPT_NAME = ''
SERVER_NAME = '30c262e75da6'
SERVER_PORT = '8000'
SERVER_PROTOCOL = 'HTTP/1.1'
SERVER_SOFTWARE = 'WSGIServer/0.2'
SHLVL = '1'
TERM = 'xterm'
TZ = 'UTC'
WEB_SERVER_PORT = '8000'
_ = './manage.py'
wsgi.errors = <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
wsgi.file_wrapper = ''
wsgi.input = <_io.BufferedReader name=7>
wsgi.multiprocess = False
wsgi.multithread = True
wsgi.run_once = False
wsgi.url_scheme = 'http'
wsgi.version = '(1, 0)'

Settings:
Using settings module aether.kernel.settings
ABSOLUTE_URL_OVERRIDES = {}
ADD_REVERSION_ADMIN = True
ADMINS = []
ALLOWED_HOSTS = ['*']
APPEND_SLASH = True
APP_LINK = 'http://aether.ehealthafrica.org'
APP_NAME = 'Aether Kernel'
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS = '********************'
AUTH_USER_MODEL = 'auth.User'
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_KEY_PREFIX = '********************'
CACHE_MIDDLEWARE_SECONDS = 600
CAS_SERVER_URL = None
CORS_ORIGIN_ALLOW_ALL = True
CSRF_COOKIE_AGE = 31449600
CSRF_COOKIE_DOMAIN = '.aether.local'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_PATH = '/'
CSRF_COOKIE_SECURE = False
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = ['.aether.local']
CSRF_USE_SESSIONS = False
DATABASES = {'default': {'ENGINE': 'django_prometheus.db.backends.postgresql', 'NAME': 'aether', 'PASSWORD': '********************', 'USER': 'postgres', 'HOST': 'db', 'PORT': '5432', 'TESTING': {'CHARSET': 'UTF8'}, 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'OPTIONS': {}, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'NAME': None, 'MIRROR': None}}}
DATABASE_ROUTERS = []
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
DATETIME_FORMAT = 'N j, Y, P'
DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%Y', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M', '%m/%d/%y']
DATE_FORMAT = 'N j, Y'
DATE_INPUT_FORMATS = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y']
DEBUG = True
DEBUG_PROPAGATE_EXCEPTIONS = False
DEBUG_TOOLBAR_CONFIG = {'SHOW_TOOLBAR_CALLBACK': <function <lambda> at 0x7fafe18ee268>, 'SHOW_TEMPLATE_CONTEXT': True}
DECIMAL_SEPARATOR = '.'
DEFAULT_CHARSET = 'utf-8'
DEFAULT_CONTENT_TYPE = 'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL = 'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE = ''
DEFAULT_TABLESPACE = ''
DISALLOWED_USER_AGENTS = []
DJANGO_STORAGE_BACKEND = 'filesystem'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_HOST_PASSWORD = '********************'
EMAIL_HOST_USER = ''
EMAIL_PORT = 25
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = '********************'
EMAIL_SUBJECT_PREFIX = '[Django] '
EMAIL_TIMEOUT = None
EMAIL_USE_LOCALTIME = False
EMAIL_USE_SSL = False
EMAIL_USE_TLS = False
FILE_CHARSET = 'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_PERMISSIONS = None
FILE_UPLOAD_TEMP_DIR = None
FIRST_DAY_OF_WEEK = 0
FIXTURE_DIRS = []
FORCE_SCRIPT_NAME = None
FORMAT_MODULE_PATH = None
FORM_RENDERER = 'django.forms.renderers.DjangoTemplates'
HOSTNAME = 'kernel.aether.local'
IGNORABLE_404_URLS = []
INSTALLED_APPS = ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.messages', 'django.contrib.postgres', 'django.contrib.sessions', 'django.contrib.staticfiles', 'storages', 'rest_framework', 'rest_framework.authtoken', 'rest_framework_csv', 'corsheaders', 'django_prometheus', 'aether.common', 'debug_toolbar', 'django_filters', 'rest_framework_filters', 'reversion', 'reversion_compare', 'aether.kernel', 'drf_yasg']
INTERNAL_IPS = []
LANGUAGES = [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI = ['he', 'ar', 'fa', 'ur']
LANGUAGE_CODE = 'en-us'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_PATH = '/'
LOCALE_PATHS = []
LOGGED_OUT_TEMPLATE = 'aether/logged_out.html'
LOGGING = {'version': 1, 'disable_existing_loggers': True, 'root': {'level': 20, 'handlers': ['aether_handler']}, 'formatters': {'verbose': {'format': '%(levelname)s  %(asctime)s  %(module)s  %(process)d  %(thread)d  %(message)s'}}, 'handlers': {'aether_handler': {'level': 20, 'class': 'logging.StreamHandler', 'formatter': 'verbose'}, 'console': {'level': 20, 'class': 'logging.StreamHandler', 'formatter': 'verbose'}}, 'loggers': {'aether': {'level': 20, 'handlers': ['console', 'aether_handler'], 'propagate': False}, 'django': {'level': 20, 'handlers': ['console', 'aether_handler'], 'propagate': False}, 'raven': {'level': 'ERROR', 'handlers': ['console', 'aether_handler'], 'propagate': False}, 'sentry.errors': {'level': 'ERROR', 'handlers': ['console', 'aether_handler'], 'propagate': False}}}
LOGGING_CLASS = 'logging.StreamHandler'
LOGGING_CONFIG = 'logging.config.dictConfig'
LOGGING_LEVEL = 20
LOGIN_REDIRECT_URL = '/accounts/profile/'
LOGIN_TEMPLATE = 'aether/login.html'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = None
MANAGERS = []
MEDIA_BASIC_URL = '/media-basic/'
MEDIA_INTERNAL_URL = '/media-internal/'
MEDIA_ROOT = '/media/'
MEDIA_URL = '/media/'
MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE = ['django_prometheus.middleware.PrometheusBeforeMiddleware', 'django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'corsheaders.middleware.CorsMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'debug_toolbar.middleware.DebugToolbarMiddleware', 'django_prometheus.middleware.PrometheusAfterMiddleware']
MIDDLEWARE_CLASSES = ['django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware']
MIGRATION_MODULES = {'kernel': 'aether.kernel.api.migrations'}
MONTH_DAY_FORMAT = 'F j'
NUMBER_GROUPING = 0
PASSWORD_HASHERS = '********************'
PASSWORD_RESET_TIMEOUT_DAYS = '********************'
PREPEND_WWW = False
REST_FRAMEWORK = {'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer', 'aether.common.drf.renderers.CustomBrowsableAPIRenderer', 'aether.common.drf.renderers.CustomAdminRenderer', 'aether.common.drf.renderers.CustomCSVRenderer'), 'DEFAULT_PARSER_CLASSES': ('rest_framework.parsers.JSONParser', 'rest_framework.parsers.FormParser', 'rest_framework.parsers.MultiPartParser'), 'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.SessionAuthentication', 'rest_framework.authentication.BasicAuthentication', 'rest_framework.authentication.TokenAuthentication'), 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',), 'DEFAULT_FILTER_BACKENDS': ('rest_framework_filters.backends.DjangoFilterBackend', 'rest_framework.filters.SearchFilter', 'rest_framework.filters.OrderingFilter'), 'DEFAULT_PAGINATION_CLASS': 'aether.common.drf.pagination.CustomPagination', 'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning'}
ROOT_URLCONF = 'aether.kernel.urls'
SECRET_KEY = '********************'
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_HSTS_SECONDS = 0
SECURE_PROXY_SSL_HEADER = None
SECURE_REDIRECT_EXEMPT = []
SECURE_SSL_HOST = None
SECURE_SSL_REDIRECT = False
SENTRY_DSN = None
SERVER_EMAIL = 'root@localhost'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_DOMAIN = '.aether.local'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_SECURE = False
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_FILE_PATH = None
SESSION_SAVE_EVERY_REQUEST = False
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE = 'aether.kernel.settings'
SHORT_DATETIME_FORMAT = 'm/d/Y P'
SHORT_DATE_FORMAT = 'm/d/Y'
SIGNING_BACKEND = 'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS = []
STATICFILES_DIRS = []
STATICFILES_FINDERS = ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT = '/var/www/static/'
STATIC_URL = '/static/'
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.media', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages', 'aether.common.context_processors.aether_context']}}]
TESTING = False
TEST_NON_SERIALIZED_APPS = []
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR = ','
TIME_FORMAT = 'P'
TIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE = 'UTC'
USE_ETAGS = False
USE_I18N = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = False
USE_TZ = True
USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False
WSGI_APPLICATION = None
X_FRAME_OPTIONS = 'SAMEORIGIN'
YEAR_MONTH_FORMAT = 'F Y'


You're seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.

"}
```

**Review by admbtlr — DISMISSED** [review]

**Review by admbtlr — APPROVED** [review]

**Comment by obdulia-losantos** [comment]
@adamvert sorry, I realized late that the schema name could be taken from the AVRO schema, and this is the way is gonna be used in Gather with the uploaded files :grimacing:

**Comment by admbtlr** [comment]
Yep, that's what I figured - makes sense

**Pull request merged**
