### PR TITLE
fix(ui): up to date with develop

### PR DESCRIPTION
**Pull request by obdulia-losantos**

### CODE REVIEW

**Comment by obdulia-losantos** [comment]
A good practice after our last nightmare :wink: 

@quesebifurcan I'm not sure if the `setup_projects` option in `entrypoint.sh` is still a thing to be fixed in the future. :thinking:

**Comment by quesebifurcan** [comment]
@obdulia-losantos yeah, that one is a bit weird. Definitely worth revisiting.

**Comment by obdulia-losantos** [comment]
@lordmallam do you mind taking a look at the failing test? :unamused: 

```
======================================================================
FAIL: test_view_pipeline_fetch (aether.ui.api.tests.test_views.ViewsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/aether/ui/api/tests/test_views.py", line 424, in test_view_pipeline_fetch
    self.assertEqual(len(response_data), 3)
AssertionError: 2 != 3
----------------------------------------------------------------------
```

**Comment by obdulia-losantos** [comment]
@quesebifurcan @lordmallam who wants to review it? :grimacing:

**Review by lordmallam — APPROVED** [review]
Looks good

**Pull request merged**
