### PR TITLE
feat(docker): health check in containers

### PR DESCRIPTION
**Pull request by obdulia-losantos**
```bash
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED              STATUS                        PORTS                                        NAMES
25465ab8755b        aether-couchdb-sync   "/code/entrypoint.sh…"   50 seconds ago       Up 48 seconds                                                              aether_couchdb-sync-rq_1
77f584a7b3fc        aether-couchdb-sync   "/code/entrypoint.sh…"   59 seconds ago       Up 55 seconds (healthy)       0.0.0.0:8006->8006/tcp                       aether_couchdb-sync_1
9c3837be6f4c        nginx:alpine          "nginx -g 'daemon of…"   59 seconds ago       Up 56 seconds (healthy)       0.0.0.0:80->80/tcp, 0.0.0.0:8443->8443/tcp   aether_nginx_1
93255d726150        aether-odk            "/code/entrypoint.sh…"   59 seconds ago       Up 57 seconds (healthy)       0.0.0.0:8002->8002/tcp                       aether_odk_1
0a086600de9b        aether-ui             "/code/entrypoint.sh…"   59 seconds ago       Up 57 seconds (healthy)       0.0.0.0:8004->8004/tcp                       aether_ui_1
9b2bec0990a6        aether-kernel         "/code/entrypoint.sh…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:8000->8000/tcp                       aether_kernel_1
db27b0633f74        postgres:9.6-alpine   "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   5432/tcp                                     aether_db_1
d810575f90ff        aether_ui-assets      "/code/conf/entrypoi…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:3004->3004/tcp                       aether_ui-assets_1
d4550d0f2431        couchdb:1.7.2         "tini -- /docker-ent…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:5984->5984/tcp                       aether_couchdb_1
1bb4ab84c9a4        redis:alpine          "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   6379/tcp                                     aether_redis_1

```

### CODE REVIEW

**Comment by admbtlr** [comment]
This looks good, but when I try `docker-compose up` I get this:
```
ERROR: for couchdb-sync-rq  Container "1d73de647730" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by obdulia-losantos** [comment]
:eyes:

**Comment by obdulia-losantos** [comment]
@adamvert could you check again?

**Comment by admbtlr** [comment]
```
ERROR: for ui  Container "c436d271dd31" is unhealthy.

ERROR: for couchdb-sync-rq  Container "781d1b2f6235" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by obdulia-losantos** [comment]
> ERROR: for couchdb-sync-rq  Container "781d1b2f6235" is unhealthy.

This error shouldn't happen because healthcheck in `couchdb-sync-rq` is disabled :scream: 

https://github.com/eHealthAfrica/aether/pull/326/files#diff-67bbea6c1714cf65fd6eaaa01a3f49eaR250

**Comment by obdulia-losantos** [comment]
Please, go to your `.env` file and set a value for `COUCHDB_SYNC_GOOGLE_CLIENT_ID`  :grimacing:

**Comment by admbtlr** [comment]
Still getting the errors after a rebuild :/

**Comment by obdulia-losantos** [comment]
Could you try again? @adamvert  :crossed_fingers:

**Comment by obdulia-losantos** [comment]
@adamvert whenever you can, and this time it's necessary to rebuild common and the containers :grimacing: 

```bash
./scripts/build_common_and_distribute.sh
docker-compose build
docker-compose up
```

**Comment by admbtlr** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Review by admbtlr — APPROVED** [review]

**Pull request merged**
