### PR TITLE
avro schema viewer array fix

### PR DESCRIPTION
**Pull request by lordmallam**
Fixes the bug that displays `You have provided an invalid schema` when using schemas with 2nd level arrays.
Example: 
`{
  "name": "Auto_2",
  "type": "record",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "a",
      "type": {
        "type": "array",
        "items": [
          {
            "name": "Auto_0",
            "type": "record",
            "fields": [
              {
                "name": "b",
                "type": "int"
              }
            ]
          },
          {
            "type": "array",
            "items": {
              "name": "Auto_1",
              "type": "record",
              "fields": [
                {
                  "name": "c",
                  "type": "int"
                }
              ]
            }
          }
        ]
      }
    }
  ]
}`

### CODE REVIEW

**Comment by quesebifurcan** [comment]
I'm seeing some issues related to the display of nested arrays. 

Example; this json data:
```
{
  "a": [
    {
      "b": [
        [
          [
            [
              {
                "c": [
                  {
                    "d": 3
                  }
                ]
              }
            ]
          ]
        ]
      ]
    }
  ]
}
```
...gives us the following result:

2018-06-25-123108_626x459

To be fair, I'm not entirely sure how it should be represented, any ideas? @lordmallam @sabeen

**Review by quesebifurcan — CHANGES_REQUESTED** [review]
Looks good, nice work! Still seeing some issues with nested arrays+objects (see comment).

**Comment by lordmallam** [comment]
That is expected behaviour, considering the depth of nested arrays and UI real estate for the schema viewer. The issue here is if we decide to cut off visualisation at a certain depth or not. This will affect how the user determines the correct path to a property for mapping purposes.

**Comment by admbtlr** [comment]
@sabeen can you take a look at lowering the size of the indentation for this? I guess this means making some changes in this block:

https://github.com/eHealthAfrica/aether/blob/develop/aether-ui/aether/ui/assets/css/_section-input.scss#L125

**Comment by sabeen** [comment]
bildschirmfoto 2018-07-03 um 15 05 27

**Review by admbtlr — APPROVED** [review]
LGTM!

**Comment by admbtlr** [comment]
@quesebifurcan can you re-review please?

**Review by quesebifurcan — APPROVED** [review]

**Pull request merged**
