### PR TITLE
feature: add salad-bar schema generator

### PR DESCRIPTION
**Pull request by shawnsarwar**
This tool allows for handling and registration of schemas from known sources. Don't be alarmed; it's 82K lines primarily because it includes the schema.org library.

The entrypoint is salad-bar/wizard.py. This is the only user facing tool.
See the README there for usage.

Beyond this, we've build a scraper that parses the vocabulary from schema.org and build a compliant linked SALAD schema. We can create new parses should we want to work with other schema library structures. If you write linked schema definitions using the CSV format that schema.org employs, we can generate new schema libraries in SALAD automatically. The path of least resistance for import of new schema libraries will probably be determined ad hoc at a later date. It may be simpler to massage them into the Schema.org CSV format (for which we have a parser) rather than writing a new parser. It's a huge pain and I don't recommend.

### CODE REVIEW

**Comment by quesebifurcan** [comment]
Is the Pipfile up to date? When running

```
pipenv --two install
pipenv shell
pipenv run python ./wizard.py
```

I get an error:

```
Traceback (most recent call last):
  File "./wizard.py", line 11, in <module>
    from saladbar import salad_handler as salad
  File "/home/fred/work/eha/repos/aether/salad-bar/saladbar/salad_handler.py", line 5, in <module>
    from schema_salad import schema, validate, jsonld_context
  File "/home/fred/.local/share/virtualenvs/salad-bar-Q_Fz2kfj/local/lib/python2.7/site-packages/schema_salad/schema.py", line 2, in <module>
    import avro
ImportError: No module named avro
```

**Comment by shawnsarwar** [comment]
@quesebifurcan I can't reproduce. Can you please:
-   delete Pipfile.lock
-   pipenv -rm
-   pipenv --two install
-  pipenv run python ./wizard.py

**Comment by quesebifurcan** [comment]
@shawnsarwar 

This was the issue I ran into: https://github.com/pypa/pipenv/issues/695#issuecomment-336515906 -- `pip lock --clear` resolved it.

I also had to do a `mkdir -p salad-bar/schemas` in order to get the wizard to run. This was the error:

```
Traceback (most recent call last):
  File "./wizard.py", line 202, in <module>
    main()
  File "./wizard.py", line 155, in main
    "Delete existing schemas before building library?"
  File "./wizard.py", line 77, in prompt_schema_clean
    contents = os.listdir(SCHEMAS)
OSError: [Errno 2] No such file or directory: 'schemas/'
```

**Comment by quesebifurcan** [comment]
Can we lint it a bit as well?

```
autopep8 --in-place --aggressive --recursive salad-bar
```

should resolve most issues.

**Review by quesebifurcan — APPROVED** [review]

**Comment by quesebifurcan** [comment]
Looks great! Can we hold off on merging it until Will has sorted the release scripts? @shawnsarwar

**Pull request merged**
