### PR TITLE
test: cover methods parseSchema, randomInput

### PR DESCRIPTION
**Pull request by jirihofman**
Added test coverage for two methods in `aether-ui/aether/ui/assets/apps/utils/avro-utils.spec.jsx`
- `parseSchema()` - checking that proper parse methid is called
- `randomInput()` - verifying that ID field gets UUID generated

Both done using Jest mocking

This is my first PR, I'm starting to look around this interesting project

### CODE REVIEW

**Comment by shawnsarwar** [comment]
Hi @jirihofman, welcome and thanks for your PR! I've requested a review from the appropriate people.

**Review by obdulia-losantos — CHANGES_REQUESTED** [review]
Hi @jirihofman,

We use `standard` in the JS side, could you remove the semicolons or the tests will not pass and add the missing whitespaces? :wink: 

https://github.com/eHealthAfrica/aether#code-style

**Comment by jirihofman** [comment]
I refactored it to standardjs format, should be ok now. I still need to get the docker up and running (windows user here)

**Comment by obdulia-losantos** [comment]
Docker works on Windows Pro https://docs.docker.com/docker-for-windows/install/
I tested it and worked perfectly. 

If you only want to run the JS tests outside docker execute the following:

```batch
cd aether-ui\aether\ui\assets
npm install
npm run test
```

**Comment by jirihofman** [comment]
> If you only want to run the JS tests outside docker execute the following:
> 
> ```batchfile
> cd aether-ui\aether\ui\assets
> npm install
> npm run test
> ```

That is what I did, it didn't change any .jsx file.

I tried the Windows Docker too, followed the instructions but got this error:

> WARNING: The KERNEL_READONLY_DB_USERNAME variable is not set. Defaulting to a blank string.
> WARNING: The KERNEL_READONLY_DB_PASSWORD variable is not set. Defaulting to a blank string.
> Traceback (most recent call last):
>   File "docker-compose", line 6, in <module>
>   File "compose\cli\main.py", line 71, in main
>   File "compose\cli\main.py", line 124, in perform_command
>   File "compose\cli\command.py", line 42, in project_from_options
>   File "compose\cli\command.py", line 128, in get_project
>   File "compose\project.py", line 101, in from_config
>   File "compose\network.py", line 320, in get_networks
>   File "compose\network.py", line 125, in true_name
>   File "compose\network.py", line 146, in _set_legacy_flag
>   File "compose\network.py", line 106, in inspect
>   File "site-packages\docker\utils\decorators.py", line 17, in wrapped
> docker.errors.NullResource: Resource ID was not provided
> [10164] Failed to execute script docker-compose

That is probably due to my lack of docker experience and I will look into it further.

I ended up using Visual Studio Code plugin, which works just fine.

**Comment by obdulia-losantos** [comment]
I can imagine that you executed the following commands, didn't you?

```bash
./scripts/build_docker_credentials.sh > .env
./scripts/build_all_containers.sh
```

Did any of them failed? It looks like you don't have your `.env` file or maybe it's a windows issue that I need to check and fix :thinking:

**Comment by jirihofman** [comment]
Finally got the docker environment running. The .sh scripts [needed to be executed in bash](https://www.thewindowsclub.com/how-to-run-sh-or-shell-script-file-in-windows-10). Then it went somewhat smoothly.

```
PS C:\Users\jirka\Desktop\VG\aether> docker-compose run --rm --no-deps ui-assets eval npm run test-lint-js

> aether-ui-assets@0.0.0 test-lint-js /code
> standard './apps/**/*.js*'

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
PS C:\Users\jirka\Desktop\VG\aether>
```

**Comment by obdulia-losantos** [comment]
Glad to hear that.

**Review by obdulia-losantos — APPROVED** [review]

**Comment by obdulia-losantos** [comment]
We need to solve a couple of issues with Travis yet. I'll merge your PRs as soon as we fixed them.

**Comment by obdulia-losantos** [comment]
Thanks for increasing our test coverage level!!!

**Comment by shawnsarwar** [comment]
Just to provide an update @jirihofman, our Travis process doesn't allow people outside the organization to trigger the automated process. We're working on migrating to CircleCI to address the issue and (finally) merge your PRs.

**Pull request merged**
