### PR TITLE
feat(kernel): csv/ xlsx export in submissions/ entities

### PR DESCRIPTION
**Pull request by obdulia-losantos**

### CODE REVIEW

**Comment by quesebifurcan** [comment]
@obdulia-losantos Was just wondering why we are merging this directly to `release-0.9` (instead of `develop`)?

**Comment by obdulia-losantos** [comment]
Good question, we can talk about the release process with @adamvert

**Comment by admbtlr** [comment]
I'm still in the process of working out the *definitive* release process (getting there, slowly...), but one thing I've realised is that sometimes we merge to develop and sometimes we merge to a release branch. I'd like to make this consistent and define the process like this:

- every feature branch should be merged to a release branch
- when a release is created, the release branch should be merged back to develop

Generally speaking, release branches are *where the action happens*, while develop just passively reflects the most recent stable version.

Does that make sense?- I'm still figuring this out, so feedback welcome!

**Comment by obdulia-losantos** [comment]
I finally managed to increase the performance. :scream: 

320,000 records in 3 minutes!!! :tada: 

The current CSVRenderer handles 100,000 in 44 seconds with limited number of records. Maybe it takes a little bit more time but without size limitation. :sweat_smile:

**Review by quesebifurcan — DISMISSED** [review]

**Comment by admbtlr** [comment]
I get healthcheck errors on the nginx container when I do `docker-compose up` :(

**Comment by obdulia-losantos** [comment]
Those errors might be fixed in  #343  :crossed_fingers:

**Comment by obdulia-losantos** [comment]
@adamvert is this PR ready to merge or still on hold?

**Comment by admbtlr** [comment]
Testing...

**Review by admbtlr — APPROVED** [review]
Took a while, but we got there in the end!

**Comment by obdulia-losantos** [comment]
I'm going to cry :cry:

**Pull request merged**
