### PR TITLE
chore: skip integration tests while failing

### PR DESCRIPTION
**Pull request by obdulia-losantos**
This is the error that randomly appears and hard to reproduce locally or in Travis.

```
=================================== FAILURES ===================================
_________________________ test_5_check_stream_entities _________________________
read_people = [{'children': None, 'dateOfBirth': 'mxhdnjku', 'description': ['zljbpxvoeus', 'zucpwto'], 'home': None, ...}, {'childr...id': '2e4aec4f-263e-4ca9-8779-ec15b5d56146'}, 'dateOfBirth': 'mcazru', 'description': 'ytslc', 'home': None, ...}, ...]
existing_entities = {'GeoLocation': [{'id': '4761ce86-8b6d-4ded-b10d-2952d4f670ba', 'merge': 'overwrite', 'modified': '2018-06-06T15:50:46...5110-4fe7-878a-9c8edb5ef34b']}, 'description': 'usmhi', 'id': '71deb318-1461-4606-9a94-da054bce3836', ...}, ...}, ...]}
    def test_5_check_stream_entities(read_people, existing_entities):
        kernel_messages = [msg.get("payload").get("id") for msg in existing_entities.get(SEED_TYPE)]
        kafka_messages = [msg.get("id") for msg in read_people]
>       assert(len(kernel_messages) == len(kafka_messages))
E       AssertionError: assert 91 == 90
E        +  where 91 = len(['851ac992-e510-421d-8419-b7618e02062b', '2ced188e-b59f-422e-a163-f93ef73fb05d', '8a733504-6689-4027-9899-02e98afbf7b4...0030-da15-43db-b1a7-1a95632fee56', '8ed7fb73-453c-4e73-aa3c-1e9e7ef6f3f5', '6434b72f-0d82-4bb0-8c3c-f49d9d454f28', ...])
E        +  and   90 = len(['96266a62-20a3-457d-b67a-a7c713585771', '8f59e243-efd6-4088-8d2c-c2dcb871bc96', '57ed27fd-e58b-42e1-901a-09256760dd3b...ec4f-263e-4ca9-8779-ec15b5d56146', '213951d4-c277-471c-b719-49a66c6aecd4', '662112e9-0228-44ea-8e38-d010915e9adb', ...])
test/test_integration.py:28: AssertionError
```

In order to get rid of annoying errors in the PRs/ deployments, no integration tests will be run till we find the reason and the solution. :crossed_fingers: 

@shawnsarwar @quesebifurcan @adamvert

### CODE REVIEW

**Review by admbtlr — APPROVED** [review]
We should definitely fix this ASAP...

**Review by quesebifurcan — APPROVED** [review]

**Comment by obdulia-losantos** [comment]
@shawnsarwar :grimacing:

**Review by shawnsarwar — APPROVED** [review]
Go for it. We can still run them manually until we figure out why the test is inconsistent.

**Comment by obdulia-losantos** [comment]
Thanks!

**Pull request merged**
